name: Go CI

on:
  pull_request:
    paths:
      - "go/**"
      - ".github/workflows/go-ci.yaml"

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    env:
      working-directory: go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.58.0
          working-directory: ${{ env.working-directory }}
      - name: Run unit tests
        working-directory: ${{ env.working-directory }}
        run: go test -v ./...
