name: Go Deploy
on:
  push:
    branches:
      - main
    paths:
      - "go/**"
      - ".github/workflows/go-deploy.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Fitbit Activity Notifier
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: go
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID}}:role/${{vars.IAM_ROLE_NAME}}
          aws-region: ${{vars.AWS_REGION}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{vars.AWS_REGION}} | docker login --username AWS --password-stdin ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com
      - name: Build Docker image
        run: docker buildx build --platform=linux/arm64 -t ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com/${{vars.REPOSITORY_NAME}}:${{github.sha}} . --load
      - name: Push Docker image to ECR
        run: docker push ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com/${{vars.REPOSITORY_NAME}}:${{github.sha}}
      - name: Deploy to Lambda
        run: aws lambda update-function-code --region ${{vars.AWS_REGION}} --function-name ${{vars.LAMBDA_FUNCTION_NAME}} --image-uri ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com/${{vars.REPOSITORY_NAME}}:${{github.sha}}
