name: terraform-apply
on:
  push:
    branches:
      - main
jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: terraform
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Detect Terraform Version
        run: |
          printf "TF_VERSION=%s" $(cat .terraform-version) >> $GITHUB_ENV
      - uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::286984104046:role/github-actions-role
          aws-region: ap-northeast-1
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
